### ISSUE TITLE
Issue with header on default dashboards.

### ISSUE THREAD

**Issue by Kilberz** [Nerwyn/material-rounded-theme#45]
Default dashboards have a very tight header. If a header bar is present then it could do with a bit of padding. If Kiosk mode is on / no header bar then no padding is required.

<img width="1328" alt="Screenshot 2024-11-11 at 20 48 41" src="https://github.com/user-attachments/assets/2dcf83c5-9d7f-4314-a648-54c1dd2884e2">

**Comment by Nerwyn** [comment]
This is because you're using the default theme at the user level but this theme at the view level. The header height is shorter for this theme, and the view top padding doesn't match the default header height. You need to either use this theme at the user level, or add your own spacer element to the view to account for it (the new heading card set to subtitle with no text in a full width section works well).
