### ISSUE TITLE
Not Fully right side bubble roundness

### ISSUE THREAD

**Issue by Grosscoder** [Nerwyn/material-rounded-theme#46]
The right side of the selected bubble is not fully rounded please fix it.

**Photo**
![Screenshot 2024-11-17 092705](https://github.com/user-attachments/assets/66d11318-62e1-4805-a9df-54cb749e50fd)

**Comment by Nerwyn** [comment]
This should be logged as a bug, and it does not contain enough information to do anything about. This issue is not present on my devices on any browser. I can't do anything about it without more information as described in the bug report template.

**Comment by Grosscoder** [comment]
There is no logs on a theme that works great, but its not rounded
correctly, how can I show you my logs you tell me.

**Comment by Nerwyn** [comment]
Not logs, logged. I don't think browser logs (right click on Home Assistant window, Inspect, Console) would be helpful here, but a closer look at the HTML elements may be. You need to include the other information from the [bug report issue template](https://github.com/Nerwyn/material-rounded-theme/blob/main/.github/ISSUE_TEMPLATE/bug_report.md), namely the browser and operating system. And to try to see if this issue is just with this browser and operating system or if it occurs with other devices and browsers as well.

That all being said I can't reproduce it on any of my devices or browsers even after messing with browser zoom and window size.

**Comment by Grosscoder** [comment]
Ok I will check it out tomorrow on my PC I'm on a mobile now.
