### ISSUE TITLE
Plant card is malformed when using material you

### ISSUE THREAD

**Issue by tomerh2001** [Nerwyn/material-rounded-theme#50]
**With** Material You:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/621ce085-3a4e-4451-874c-284d83fd5bd7" />

**Without** Material You:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/96db7805-48c5-4e18-876a-26eb0541c080" />

Card: https://github.com/Olen/lovelace-flower-card

**Comment by Nerwyn** [comment]
The header image cut off issue is also present in 2.1.10, and is due to [a fix I made for header/footer graph overflows](https://github.com/Nerwyn/material-rounded-theme/blob/3.0.0/src/common/card.css#L9-L19). I can tighten up the header/footer selectors to also check for the graphs and that should fix that. The cut off bar values is due to the card missusing the `header` class for labels, but the same fix should work for that as well?

Try the 3.0.0 alpha and see if it fixes it for you.

**Comment by Nerwyn** [comment]
[Fixed in 3.0.1.](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.1)
